import type { LaunchComposition } from "./launch-types";

export function launchTemplate(
  videoAsset = "assets/capture.mp4",
  clipDurationS = 12,
): LaunchComposition {
  const firstDuration = Math.min(5, Math.max(0.5, clipDurationS / 2));
  const secondStart = firstDuration;
  const secondDuration = Math.min(6, Math.max(0.5, clipDurationS - secondStart));
  return {
    version: 1,
    output: { width: 1920, height: 1080, fps: 30 },
    theme: {
      canvas: "#F5F2EA",
      ink: "#172E28",
      surface: "#DCE5D8",
      accent: "#214F41",
      dark: "#10231E",
      fontFamily: "Avenir Next, Avenir, Helvetica Neue, Noto Sans, sans-serif",
    },
    scenes: [
      {
        id: "opening",
        type: "title",
        durationS: 3,
        lines: ["Real clicks.", "Ready for launch."],
        brand: "Open Take",
        staggerS: 0.38,
        transition: { type: "fade", durationS: 0.45 },
      },
      {
        id: "capture",
        type: "footage",
        durationS: firstDuration,
        asset: videoAsset,
        trimStartS: 0,
        fit: "contain",
        frame: { inset: 92, radius: 28 },
        caption: "Capture the real thing.",
        transition: { type: "slide", durationS: Math.min(0.5, firstDuration / 3) },
      },
      {
        id: "compose",
        type: "ui-morph",
        states: [
          {
            icon: "record",
            label: "Record",
            prompt: "",
            transitionS: 0.55,
            typeDelayS: 0.54,
            typeS: 0.01,
            holdS: 0,
          },
          {
            icon: "record",
            label: "Record",
            prompt: "Record the real app.",
            transitionS: 0.55,
            typeDelayS: 0.18,
            typeS: 0.7,
            holdS: 0.32,
            panelWidth: 1100,
            panelHeight: 218,
          },
          {
            icon: "style",
            label: "Style",
            prompt: "Make it cinematic.",
            transitionS: 0.6,
            typeDelayS: 0.6,
            typeS: 0.7,
            holdS: 0.5,
            panelWidth: 1040,
            panelHeight: 218,
          },
          {
            icon: "refine",
            label: "Refine",
            prompt: "Tighten the focus.",
            transitionS: 0.6,
            typeDelayS: 0.6,
            typeS: 0.7,
            holdS: 1.15,
            panelWidth: 1060,
            panelHeight: 218,
          },
        ],
        eyebrow: "Make it yours.",
        panel: { width: 1100, compactHeight: 112, expandedHeight: 218, radius: 34 },
        transition: { type: "fade", durationS: 0.35 },
      },
      {
        id: "editable",
        type: "footage",
        durationS: secondDuration,
        asset: videoAsset,
        trimStartS: secondStart,
        fit: "contain",
        background: "dark",
        frame: { inset: 84, radius: 28 },
        caption: "Keep every detail editable.",
        transition: { type: "slide", durationS: Math.min(0.5, secondDuration / 3) },
      },
      {
        id: "payoff",
        type: "title",
        durationS: 3,
        background: "dark",
        lines: ["Record.", "Compose.", "Refine."],
        staggerS: 0.42,
        transition: { type: "fade", durationS: 0.4 },
      },
      {
        id: "end",
        type: "end-card",
        durationS: 3,
        headline: "Your next release. In motion.",
        brand: "Open Take",
        cta: "npm create open-take@latest",
        transition: { type: "fade", durationS: 0.45 },
      },
    ],
  };
}
